# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 983872e82eb075d7b1db4fccbfd663ac9b0917483ea1c902b6e00ad882e6a1a89f9fade3b7b88d1c89ef1113bb410ccf71a4fa8c660434e376856f2b114bf399

test:
  secret_key_base: a29bf919a24f6da04cf194c54006227a27aa41651fe98517795ac902dbd82bec8e400a424614e6ae0b02bf0e90b66a4f07e6c9c3ca08483e13f11d6fffc3c32a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
